version: "3"

services:
  db:
    container_name: db
    image: 'mongo:4.4.13'
    restart: always
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
    ports:
      - "27017:27017"
    networks:
      - stagingnetwork

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      - db
    networks:
      - stagingnetwork

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG

networks:
  stagingnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1